-- Habilitar extensão UUID (opcional, mas boa prática)
create extension if not exists "uuid-ossp";

-- 1. Tabela de Alunos
create table if not exists alunos (
  id bigint generated by default as identity primary key,
  nome text not null,
  data_nascimento date not null,
  rg text not null,
  sexo text,
  gravida text default 'Não',
  pcd text default 'Não',
  modalidade text not null,
  turma text not null,
  data_entrada date not null,
  data_saida date,
  data_cadastro timestamp with time zone default timezone('utc'::text, now()),
  ativo boolean default true
);

-- 2. Tabela de Usuários (Admin/Professores/Secretaria)
create table if not exists usuarios (
  username text primary key,
  tipo text not null check (tipo in ('professor', 'secretaria', 'admin')),
  nome text,
  modalidade text,
  senha text not null, -- Idealmente deve ser hash, mas mantendo compatibilidade simples
  ativo boolean default true
);

-- 3. Tabela de Listas de Presença (Cabeçalho)
create table if not exists listas (
  id bigint generated by default as identity primary key,
  nome text not null,
  mes text not null,
  ano integer not null,
  modalidade text not null,
  turma text not null,
  data_criacao timestamp with time zone default timezone('utc'::text, now()),
  salva boolean default false
);

-- 4. Tabela de Alunos na Lista (Relacionamento N:N entre Lista e Aluno)
create table if not exists lista_alunos (
  id bigint generated by default as identity primary key,
  lista_id bigint references listas(id) on delete cascade,
  aluno_id bigint references alunos(id) on delete cascade,
  aluno_nome text, -- Cache do nome para histórico
  status text
);

-- 5. Tabela de Chamadas (Registro diário de presença)
create table if not exists chamadas (
  id bigint generated by default as identity primary key,
  lista_id bigint references listas(id) on delete cascade,
  data_chamada date not null,
  aluno_id bigint references alunos(id) on delete cascade,
  status text not null -- 'presente', 'ausente', 'justificado'
);

-- Políticas de Segurança (RLS) - Configuração permissiva inicial
alter table alunos enable row level security;
create policy "Acesso público alunos" on alunos for all using (true);

alter table usuarios enable row level security;
create policy "Acesso público usuarios" on usuarios for all using (true);

alter table listas enable row level security;
create policy "Acesso público listas" on listas for all using (true);

alter table lista_alunos enable row level security;
create policy "Acesso público lista_alunos" on lista_alunos for all using (true);

alter table chamadas enable row level security;
create policy "Acesso público chamadas" on chamadas for all using (true);
